// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Paquetes.Entities.Entities
{
    public partial class tbPaquetes
    {
        public int paqu_ID { get; set; }
        public int paqu_Cliente { get; set; }
        public int sucu_ID { get; set; }
        public int paqu_Peso { get; set; }
        public bool paqu_Fragil { get; set; }
        public int meto_ID { get; set; }
        public string muni_ID { get; set; }
        public string paqu_DireccionExacta { get; set; }
        public DateTime paqu_FechaSalida { get; set; }
        public int? trac_ID { get; set; }
        public DateTime? paqu_FechaCreacion { get; set; }
        public int paqu_UserCreacion { get; set; }
        public DateTime? paqu_FechaModificacion { get; set; }
        public int? paqu_UserModificacion { get; set; }
        public bool? paqu_Estado { get; set; }

        public virtual tbMetodosPago meto { get; set; }
        public virtual tbMunicipios muni { get; set; }
        public virtual tbPersonas paqu_ClienteNavigation { get; set; }
        public virtual tbUsuarios paqu_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios paqu_UserModificacionNavigation { get; set; }
        public virtual tbSucursales sucu { get; set; }
        public virtual tbTracking trac { get; set; }
    }
}