// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Paquetes.Entities.Entities
{
    public partial class tbPersonas
    {
        public tbPersonas()
        {
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int pers_ID { get; set; }
        public string pers_Identidad { get; set; }
        public string pers_Nombres { get; set; }
        public string pers_Apellidos { get; set; }
        public string pers_Sexo { get; set; }
        public bool? pers_EsAdmin { get; set; }
        public DateTime? pers_FechaCreacion { get; set; }
        public int pers_UserCreacion { get; set; }
        public DateTime? pers_FechaModificacion { get; set; }
        public int? pers_UserModificacion { get; set; }
        public bool? pers_Estado { get; set; }

        public virtual tbUsuarios pers_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios pers_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}