// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Paquetes.Entities.Entities
{
    public partial class tbTracking
    {
        public tbTracking()
        {
            tbPaquetes = new HashSet<tbPaquetes>();
        }

        public int trac_ID { get; set; }
        public string trac_Nombre { get; set; }
        public DateTime? trac_FechaCreacion { get; set; }
        public int trac_UserCreacion { get; set; }
        public DateTime? trac_FechaModificacion { get; set; }
        public int? trac_UserModificacion { get; set; }
        public bool? trac_Estado { get; set; }

        public virtual ICollection<tbPaquetes> tbPaquetes { get; set; }
    }
}