// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Paquetes.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            Inverseuser_UserCreacionNavigation = new HashSet<tbUsuarios>();
            Inverseuser_UserModificacionNavigation = new HashSet<tbUsuarios>();
            tbMetodosPagometo_UserCreacionNavigation = new HashSet<tbMetodosPago>();
            tbMetodosPagometo_UserModificacionNavigation = new HashSet<tbMetodosPago>();
            tbPaquetespaqu_UserCreacionNavigation = new HashSet<tbPaquetes>();
            tbPaquetespaqu_UserModificacionNavigation = new HashSet<tbPaquetes>();
            tbPersonaspers_UserCreacionNavigation = new HashSet<tbPersonas>();
            tbPersonaspers_UserModificacionNavigation = new HashSet<tbPersonas>();
            tbSucursalessucu_UserCreacionNavigation = new HashSet<tbSucursales>();
            tbSucursalessucu_UserModificacionNavigation = new HashSet<tbSucursales>();
        }

        public int user_ID { get; set; }
        public string user_Username { get; set; }
        public string user_Contrasena { get; set; }
        public int pers_ID { get; set; }
        public DateTime? user_FechaCreacion { get; set; }
        public int? user_UserCreacion { get; set; }
        public DateTime? user_FechaModificacion { get; set; }
        public int? user_UserModificacion { get; set; }
        public bool? user_Estado { get; set; }

        public virtual tbPersonas pers { get; set; }
        public virtual tbUsuarios user_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios user_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseuser_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseuser_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbMetodosPago> tbMetodosPagometo_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbMetodosPago> tbMetodosPagometo_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbPaquetes> tbPaquetespaqu_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbPaquetes> tbPaquetespaqu_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbPersonas> tbPersonaspers_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbPersonas> tbPersonaspers_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbSucursales> tbSucursalessucu_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbSucursales> tbSucursalessucu_UserModificacionNavigation { get; set; }
    }
}