// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Paquetes.Entities.Entities
{
    public partial class VW_PaquetesXMunicipio
    {
        public string muni_ID { get; set; }
        public string muni_Descripcion { get; set; }
        public int? cantidad_Paquetes { get; set; }
    }
}