// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Paquetes.Entities.Entities
{
    public partial class VW_Register
    {
        public string pers_Identidad { get; set; }
        public string pers_Nombres { get; set; }
        public string pers_Apellidos { get; set; }
        public string pers_Sexo { get; set; }
        public bool? pers_EsAdmin { get; set; }
        public int user_ID { get; set; }
        public string user_Username { get; set; }
        public string user_Contrasena { get; set; }
    }
}