// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Paquetes.Entities.Entities
{
    public partial class VW_tbEmpleados
    {
        public int pers_ID { get; set; }
        public string pers_Identidad { get; set; }
        public string pers_Nombres { get; set; }
        public string pers_Apellidos { get; set; }
        public string EmpleadoNombreCompleto { get; set; }
        public string pers_Sexo { get; set; }
        public bool? pers_EsAdmin { get; set; }
        public DateTime? pers_FechaCreacion { get; set; }
        public int pers_UserCreacion { get; set; }
        public DateTime? pers_FechaModificacion { get; set; }
        public int? pers_UserModificacion { get; set; }
        public bool? pers_Estado { get; set; }
    }
}