// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Paquetes.Entities.Entities
{
    public partial class VW_tbUsuarios
    {
        public int user_ID { get; set; }
        public string user_Username { get; set; }
        public string user_Contrasena { get; set; }
        public int pers_ID { get; set; }
        public bool? pers_EsAdmin { get; set; }
        public string user_NombreCompleto { get; set; }
        public string pers_Sexo { get; set; }
        public DateTime? user_FechaCreacion { get; set; }
        public int? user_UserCreacion { get; set; }
        public DateTime? user_FechaModificacion { get; set; }
        public int? user_UserModificacion { get; set; }
        public bool? user_Estado { get; set; }
    }
}